#!/usr/bin/env ruby
# frozen_string_literal: true

require 'colorize'

def containers
  x = `docker ps`

  l = []
  x.split("\n").each do |line|
    y = line.chomp.split(/\s+/)
    next if y[-1] == 'NAMES'

    l << [y[-1], y[0]]
  end

  l.sort
end

c = containers

unless c.any?
  puts 'There are no running containers'.red
  exit 1
end

puts '==> Available running containers'.bold

c.each_with_index do |x, i|
  puts "    #{i + 1} #{x[0].blue}"
end

loop do
  print("Select [1-#{c.size}] ".bold)
  opt = gets.to_i

  next unless opt >= 1 && opt <= c.size

  cmd = "docker exec -it #{c[opt - 1][1]} bash"
  puts "    #{cmd}".green
  system(cmd)
  exit 0
end
